// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADtWMv2lbXwzUHcFp_3rTr6Ao4wvNQS6c',
    appId: '1:18426260782:web:f024be887ade7f463ddebf',
    messagingSenderId: '18426260782',
    projectId: 'crystalappyuki',
    authDomain: 'crystalappyuki.firebaseapp.com',
    storageBucket: 'crystalappyuki.firebasestorage.app',
    measurementId: 'G-4NC5WT2C13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2i_nfzaW0hB1Jnd2pixjFUnZA8PT5eRs',
    appId: '1:18426260782:android:5e6d2e565efa9cd63ddebf',
    messagingSenderId: '18426260782',
    projectId: 'crystalappyuki',
    storageBucket: 'crystalappyuki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATmxNfQnffKK9drg1xxSve3Vs98s6_dSQ',
    appId: '1:18426260782:ios:2c19579663c42adb3ddebf',
    messagingSenderId: '18426260782',
    projectId: 'crystalappyuki',
    storageBucket: 'crystalappyuki.firebasestorage.app',
    iosBundleId: 'com.crimsonprism.crystalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATmxNfQnffKK9drg1xxSve3Vs98s6_dSQ',
    appId: '1:18426260782:ios:2c19579663c42adb3ddebf',
    messagingSenderId: '18426260782',
    projectId: 'crystalappyuki',
    storageBucket: 'crystalappyuki.firebasestorage.app',
    iosBundleId: 'com.crimsonprism.crystalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADtWMv2lbXwzUHcFp_3rTr6Ao4wvNQS6c',
    appId: '1:18426260782:web:4841c071868fe8703ddebf',
    messagingSenderId: '18426260782',
    projectId: 'crystalappyuki',
    authDomain: 'crystalappyuki.firebaseapp.com',
    storageBucket: 'crystalappyuki.firebasestorage.app',
    measurementId: 'G-59XC5R1JD5',
  );
}
